### ISSUE TITLE
Tooltip.Provider - No Provider in tooltip.index.ts

### ISSUE THREAD

**Issue by st-clair-clarke** [Tsuzat/ShadEditor#2]
Hi
I am traying to use the ShadEditor. 

I follow the instructions and most of the components seem to be present. Howecer the Tooltip.Provider cannot be found.

The tooltip.index and tooltip.content svelte files are shown below

**tooltip index.ts file**
```
import { Tooltip as TooltipPrimitive } from "bits-ui";
import Content from "./tooltip-content.svelte";

const Root = TooltipPrimitive.Root;
const Trigger = TooltipPrimitive.Trigger;

export {
	Root,
	Trigger,
	Content,
	//
	Root as Tooltip,
	Content as TooltipContent,
	Trigger as TooltipTrigger,
};

```

**tooltip-content.svelte**
```
<script lang="ts">
  import { Tooltip as TooltipPrimitive } from 'bits-ui'
  import { cn, flyAndScale } from '@medsoft/shared/utils'

  type $$Props = TooltipPrimitive.ContentProps

  let className: $$Props['class'] = undefined
  export let sideOffset: $$Props['sideOffset'] = 4
  export let transition: $$Props['transition'] = flyAndScale
  export let transitionConfig: $$Props['transitionConfig'] = {
    y: 8,
    duration: 150,
  }
  export { className as class }
</script>

<TooltipPrimitive.Content
  {transition}
  {transitionConfig}
  {sideOffset}
  class={cn(
    'bg-primary text-primary-foreground z-50 overflow-hidden rounded-md px-3 py-1.5 text-xs',
    className,
  )}
  {...$$restProps}
>
  <slot />
</TooltipPrimitive.Content>

```

Where ever Tooltip.Provider is used, the app cannot find it as shown in the screenshot below:

![image](https://github.com/user-attachments/assets/e612df40-b615-43c5-9596-b50058f8ac36)

**Comment by Tsuzat** [comment]
I'm suspecting that you might not be using "next" shadcn-svelte (for svelte5). If you're not using it then please upgrade it to "next" or alternatively you can change the code for tooltip to make it work with your current shadcn-svelte.

**Comment by Tsuzat** [comment]
>I also attempt to remove the Provider but that too generated errors

It'll not work as I just saw the API of the components (latest vs next), and it's written differently. 

You should be using shadcn-svelte@next, as the project usages it's components. Please refer to [installation](https://shad-editor.tsuzat.com/docs#Installation).
