### ISSUE TITLE
Package manager not detected on monorepo

### ISSUE THREAD

**Issue by unlocomqx** [Tsuzat/ShadEditor#3]
Hi
Since a monorepo has a lock file only in the root, the init command won't be able to determine the current PM when executed in a sub-package dir.

https://github.com/Tsuzat/ShadEditor/blob/b2e7877dc17c3033f6a9b1be249560c523334dd2/bin/cli.js#L48-L54

In my case, it was trying to npm on a pnpm monorepo, thus resulting in an error

```text
Components copied to ./src/lib/components/shad-editor
Installing dependencies using npm...
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```

Shadcn uses this [package](https://www.npmjs.com/package/package-manager-detector) to detect the PM reliably.

https://github.com/huntabyte/shadcn-svelte/blob/5cd7061ec8025c7fd75e5ce9eeae232191ebde5a/packages/cli/src/utils/auto-detect.ts#L100-L122

I'm using turborepo with pnpm

**Comment by Tsuzat** [comment]
Feel free to reopen the issue if it's not resolved. 
Happy Coding
