### ISSUE TITLE
Incompatibility with tailwind 4 that is coming

### ISSUE THREAD

**Issue by andreineamtu** [Tsuzat/ShadEditor#4]
Hi, 

I'm trying to use the editor in a project that uses already tailwind 4 beta but I can't as it has tailwind 3 directives in the style.

Will there be an update regarding this?

**Comment by Tsuzat** [comment]
ShadEditor's UI depends on Shadcn which usage tailwind 3 (last time I checked, I might be wrong). Moreover, My main focus is to include few more features. I'll be moving to tailwind 4, once there is a stable release. For now, You can mannually try to edit the tailwind classes in code.

Sorry for the inconvenience and Happy Coding.
